In [108]:
#Saturdays.AI, Practica Pandas, Xochitl Arroyo 
import numpy as np
import pandas as pd
def quality_report(data):

    """This method will do a basic data quality report for a data frame"""
        
    if (type(data) != pd.core.frame.DataFrame):
        raise TypeError("Data must be pandas.core.frame.DataFrame")
    else: 
        columns = list(data.columns.values)
        data_type = pd.DataFrame(data.dtypes, columns=['Data type'])
        missing_data = pd.DataFrame(
        data.isnull().sum(), columns=['missing values'])
        present_data = pd.DataFrame(data.count(), columns=['present values'])
        unique_values = pd.DataFrame(columns=['unique values'])
        minimum_values = pd.DataFrame(columns=['minimum values'])
        max_values = pd.DataFrame(columns=['maximun values'])
        
        for i in columns:
            unique_values.loc[i] = [data[i].nunique()]
            try:
                minimum_values.loc[i] = [data[i].min()]
                max_values.loc[i] = [data[i].max()]
            except:
                pass
        
        DQ_report = data_type.join(missing_data).join(present_data).join(
        unique_values).join(minimum_values).join(max_values)
    
    return DQ_report
csv_original = 'DataSetNike.csv'
dataset_original = pd.read_csv(csv_original, encoding='latin-1', low_memory=False)
df = pd.DataFrame(dataset_original, columns=['Material', 'Date', 'Units'])
df.columns = ['Codigo','Date', 'Units']
df=df[df.Units > 1]
df.dropna()
df['Date'] = pd.to_datetime(df['Date'])
df['Month'] = df['Date'].dt.strftime('%m')
df['Year'] = df['Date'].dt.year
df.set_index(['Month','Year'])
print(df.dtypes)
table = df.pivot_table(values='Units', index=['Codigo', 'Year'],columns = 'Month', aggfunc=np.sum)
table.columns = ['Enero','Febrero','Marzo','Abril','Mayo','Junio','Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre']
table= table.fillna(0)
print(table)
quality_report(table)

Codigo            object
Date      datetime64[ns]
Units              int64
Month             object
Year               int64
dtype: object
                 Enero  Febrero  Marzo  Abril  Mayo  Junio  Julio  Agosto  \
Codigo     Year
145700-BAJ 2018   25.0      2.0    0.0    0.0   0.0    0.0    0.0     0.0
145702-TAB 2017    0.0      0.0    0.0    0.0   0.0    0.0    0.0     0.0
145703-CAK 2017    0.0      0.0    0.0    0.0   0.0    0.0    0.0     0.0
145704-LAT 2018    0.0      4.0    4.0    0.0   0.0    2.0    0.0     0.0
145706-DAL 2017    0.0      0.0    0.0    0.0   0.0    0.0    0.0     0.0
145707-MAU 2017    0.0      0.0    0.0    0.0   0.0    0.0    0.0     0.0
145708-VAD 2017    0.0      0.0    0.0    0.0   0.0    0.0    0.0     0.0
           2018    2.0      0.0    0.0    0.0   0.0    0.0    0.0     0.0
145710-NAV 2018    0.0      0.0    0.0    0.0   0.0    2.0    0.0     0.0
145711-WAE 2018    0.0      0.0    2.0    0.0   0.0    0.0    0.0     0.0
145715-GAO 2017    0.0      0.0    0.0    0.0   0.0    0.0    0.0     0.0
145716-PAX 2018    0.0      0.0    2.0    0.0   0.0    0.0    0.0     0.0
145717-YAG 2018    0.0      6.0    2.0    0.0   0.0    0.0    0.0    26.0
145718-HAP 2018    0.0      0.0    0.0    4.0  14.0    2.0    0.0     0.0
145720-ZAH 2018    0.0      0.0    0.0    0.0   0.0    0.0    0.0    30.0
145721-IAQ 2018    0.0      0.0    0.0    0.0   0.0    0.0    4.0     0.0
145722-RAZ 2017    0.0      0.0    0.0    0.0   0.0    0.0    0.0     0.0
145725-SBA 2018    0.0      0.0    0.0   12.0  15.0    0.0    0.0     0.0
145726-BBJ 2017    0.0      0.0    0.0    0.0   0.0    0.0    0.0     0.0
145727-KBS 2018    0.0      0.0    0.0   36.0   2.0    0.0    2.0     0.0
145737-WBE 2018    0.0      0.0    0.0    4.0   0.0    4.0    0.0     6.0
145738-FBN 2018    0.0      6.0    0.0    0.0   0.0    0.0    0.0     0.0
145740-XBF 2017    0.0      0.0    0.0    0.0   0.0    0.0    0.0     0.0
145741-GBO 2017    0.0      0.0    0.0    0.0   0.0    0.0    0.0     0.0
           2018    0.0      4.0    0.0    0.0   0.0    0.0    0.0     0.0
145745-QBY 2018   10.0      0.0    0.0    0.0   0.0    0.0    0.0     0.0
145746-ZBH 2017    0.0      0.0    0.0    0.0   0.0    0.0    0.0     0.0
           2018    0.0      2.0    0.0    0.0   0.0    0.0    0.0     0.0
145749-ACI 2018    0.0      0.0    0.0    0.0   2.0    0.0    0.0     0.0
145751-SCA 2018    2.0      0.0    0.0    0.0   0.0    0.0    0.0     0.0
...                ...      ...    ...    ...   ...    ...    ...     ...
995574-LYT 2017    0.0      0.0    0.0    0.0   0.0    0.0    0.0     0.0
995592-DYL 2018   13.0      8.0    3.0   12.0   2.0    0.0    0.0     0.0
995601-MYU 2018    0.0      0.0    0.0    0.0   0.0    4.0    0.0     6.0
995610-VYD 2017    0.0      0.0    0.0    0.0   0.0    0.0    0.0     0.0
995619-EYM 2018    0.0      0.0    0.0    0.0   0.0    0.0    0.0     0.0
995628-NYV 2017    0.0      0.0    0.0    0.0   0.0    0.0    0.0     0.0
995637-WYE 2017    0.0      0.0    0.0    0.0   0.0    0.0    0.0     0.0
995646-FYN 2018    0.0      0.0   27.0    0.0   6.0    0.0    0.0     0.0
995655-OZW 2017    0.0      0.0    0.0    0.0   0.0    0.0    0.0     0.0
995673-GZO 2018    0.0      0.0    0.0    0.0  29.0    0.0    0.0     0.0
995682-PZX 2018    0.0      0.0    0.0   17.0   0.0    0.0    0.0     0.0
995700-HZP 2018    0.0      8.0   18.0   10.0   5.0    0.0    0.0     0.0
995709-QZY 2018    2.0      0.0    0.0    0.0   0.0    0.0    0.0     0.0
995736-RZZ 2017    0.0      0.0    0.0    0.0   0.0    0.0    0.0     0.0
           2018    0.0      0.0    0.0    2.0   0.0    0.0    0.0     0.0
995745-AZI 2017    0.0      0.0    0.0    0.0   0.0    0.0    0.0     0.0
995772-BZJ 2018    3.0      0.0    5.0    0.0   0.0    0.0    0.0     0.0
995781-KZS 2018    2.0      0.0    0.0    0.0   0.0    0.0    2.0     0.0
995790-TZB 2017    0.0      0.0    0.0    0.0   0.0    0.0    0.0     0.0
           2018   32.0     31.0   27.0    2.0  15.0    2.0   10.0     5.0
995817-UZC 2018    0.0      0.0    0.0    0.0   0.0    0.0    2.0     0.0
995826-DZL 2018    0.0      0.0    0.0    0.0   0.0    2.0    5.0     2.0
995835-MZU 2018    0.0      0.0    0.0    0.0   0.0    0.0    0.0     0.0
995844-VZD 2017    0.0      0.0    0.0    0.0   0.0    0.0    0.0     0.0
           2018    2.0      0.0    0.0    0.0   2.0    0.0    0.0     0.0
995853-EZM 2018    0.0     14.0    0.0    0.0   0.0    0.0    0.0     0.0
995862-NZV 2017    0.0      0.0    0.0    0.0   0.0    0.0    0.0     0.0
           2018    2.0      0.0    0.0    0.0   0.0    0.0    0.0     0.0
995871-WZE 2018   12.0      4.0    0.0    0.0   0.0    0.0    0.0     0.0
995880-FZN 2018    0.0      0.0    0.0    0.0   0.0    0.0    0.0     2.0

                 Septiembre  Octubre  Noviembre  Diciembre
Codigo     Year
145700-BAJ 2018         0.0      0.0        0.0        0.0
145702-TAB 2017         0.0     10.0        0.0        0.0
145703-CAK 2017         0.0      0.0        2.0        0.0
145704-LAT 2018         0.0      0.0        0.0        0.0
145706-DAL 2017         0.0      0.0       13.0        0.0
145707-MAU 2017         0.0      0.0        2.0        0.0
145708-VAD 2017         2.0      0.0        0.0        0.0
           2018         0.0      0.0        0.0        0.0
145710-NAV 2018         0.0      0.0        0.0        0.0
145711-WAE 2018         0.0      0.0        0.0        0.0
145715-GAO 2017         0.0      0.0        0.0        2.0
145716-PAX 2018         0.0      0.0        0.0        0.0
145717-YAG 2018         0.0      0.0        0.0        0.0
145718-HAP 2018         0.0      0.0        0.0        0.0
145720-ZAH 2018        28.0      0.0        0.0        0.0
145721-IAQ 2018         4.0      0.0        0.0        0.0
145722-RAZ 2017         4.0      2.0        4.0        0.0
145725-SBA 2018         0.0      0.0        0.0        0.0
145726-BBJ 2017        10.0      0.0        5.0        0.0
145727-KBS 2018         0.0      0.0        0.0        0.0
145737-WBE 2018         0.0      0.0        0.0        0.0
145738-FBN 2018         0.0      0.0        0.0        0.0
145740-XBF 2017         0.0      0.0        4.0        0.0
145741-GBO 2017         0.0      0.0        6.0       10.0
           2018         0.0      0.0        0.0        0.0
145745-QBY 2018         0.0      0.0        0.0        0.0
145746-ZBH 2017         0.0      2.0        0.0        0.0
           2018         2.0      0.0        0.0        0.0
145749-ACI 2018         0.0      0.0        0.0        0.0
145751-SCA 2018         0.0      0.0        0.0        0.0
...                     ...      ...        ...        ...
995574-LYT 2017        10.0      0.0        2.0        0.0
995592-DYL 2018         0.0      0.0        0.0        0.0
995601-MYU 2018        12.0      0.0        0.0        0.0
995610-VYD 2017         7.0      6.0        0.0        0.0
995619-EYM 2018        23.0      0.0        0.0        0.0
995628-NYV 2017         0.0      0.0        5.0        0.0
995637-WYE 2017         0.0      0.0        4.0        4.0
995646-FYN 2018         0.0      0.0        0.0        0.0
995655-OZW 2017         4.0      2.0       18.0        0.0
995673-GZO 2018         0.0      0.0        0.0        0.0
995682-PZX 2018         0.0      0.0        0.0        0.0
995700-HZP 2018         0.0      0.0        0.0        0.0
995709-QZY 2018         0.0      0.0        0.0        0.0
995736-RZZ 2017         0.0      0.0        2.0        0.0
           2018         0.0      0.0        0.0        0.0
995745-AZI 2017         2.0      4.0        0.0        0.0
995772-BZJ 2018         2.0      0.0        0.0        0.0
995781-KZS 2018         0.0      0.0        0.0        0.0
995790-TZB 2017         0.0      0.0        0.0        5.0
           2018         4.0      0.0        0.0        0.0
995817-UZC 2018         2.0      0.0        0.0        0.0
995826-DZL 2018         0.0      0.0        0.0        0.0
995835-MZU 2018        48.0      0.0        0.0        0.0
995844-VZD 2017         0.0      0.0        0.0        5.0
           2018         0.0      0.0        0.0        0.0
995853-EZM 2018         0.0      0.0        0.0        0.0
995862-NZV 2017         0.0      0.0        0.0        2.0
           2018         0.0      0.0        0.0        0.0
995871-WZE 2018         6.0      0.0        0.0        0.0
995880-FZN 2018         0.0      0.0        0.0        0.0

[3104 rows x 12 columns]

,Data type,missing values,present values,unique values,minimum values,maximun values
Enero,float64,0,3104,41,0.0,70.0
Febrero,float64,0,3104,27,0.0,31.0
Marzo,float64,0,3104,29,0.0,39.0
Abril,float64,0,3104,57,0.0,174.0
Mayo,float64,0,3104,29,0.0,43.0
Junio,float64,0,3104,13,0.0,18.0
Julio,float64,0,3104,14,0.0,16.0
Agosto,float64,0,3104,24,0.0,33.0
Septiembre,float64,0,3104,30,0.0,59.0
Octubre,float64,0,3104,17,0.0,19.0
Noviembre,float64,0,3104,30,0.0,133.0
Diciembre,float64,0,3104,25,0.0,133.0